### ISSUE TITLE
Issue using Wave

### ISSUE THREAD

**Issue by weekndds** [Incognito-Tabs/Roblox-WS-Execution#4]
![image](https://github.com/user-attachments/assets/f8620e8c-2b23-42e7-9f61-eed8c96a96ab)

This happens when I try decompiling a script using Wave.
`setclipboard(decompile(instancePath))`

Works perfectly fine using the actual interface for Wave, but not with WS execution.

**Comment by Incognito-Tabs** [comment]
Wave has an issue with task library and the client.lua uses task.wait, i replaced it with wait() should be fixed now.
If it's not fixed this is an issue with wave not the script.

**Comment by cantwish** [comment]
> Wave has an issue with task library and the client.lua uses task.wait, i replaced it with wait() should be fixed now. If it's not fixed this is an issue with wave not the script.

love u
